<section class="riskyde" id="riskyde">
	<div class="container">
		<div class="section-title" data-aos="fade-up">
			<h2>High Risk Countries</h2>
		</div>
		<div class="row content">
			<div class="col-lg-6" data-aos="fade-up" data-aos-delay="150">
				<p style="text-align:justify">
				<p>The following countries are considered as high-risk countries. In order to place orders involving bank accounts located in one of those countries, it is required to have successfuly gone through the KYC process.</p>
					Afghanistan,
					Albania,
					Algeria,
					American Samoa,
					Angola,
					Anguilla,
					Antarctic Treaty area,
					Antigua and Barbuda,
					Aruba,
					Azerbaijan,
					Bahamas,
					Bahrain,
					Bangladesh,
					Barbados,
					Belarus,
					Belize,
					Benin,
					Bermuda,
					Bolivia,
					Bosnia and Herzegovina,
					Botswana,
					Bouvet Island,
					British Indian Ocean Territory,
					British Virgin Islands,
					Burkina Faso,
					Burundi,
					Cambodia,
					Cameroon,
					Caribbean Netherlands,
					Cayman Islands,
					Central African Republic,
					Chad,
					Christmas Island,
					Cocos (Keeling) Islands,
					Colombia,
					Comoros,
					Cook Islands,
					Cuba,
					Curaçao,
					Democratic Republic of the Congo,
					Djibouti,
					Dominica,
					Dominican Republic,
					East Timor,
					Ecuador,
					Equatorial Guinea,
					Eritrea,
					Eswatini,
					Ethiopia,
					Falkland Islands,
					Faroe Islands,
					Federated States of Micronesia,
					Fiji,
					French Southern and Antarctic Lands,
					Gabon,
					Gambia,
					Ghana,
					Gibraltar,
					Greenland,
					Grenada,
					Guam,
					Guernsey,
					Guinea,
					Guinea-Bissau,
					Guyana,
					Haiti,
					Heard Island and McDonald Islands,
					Honduras,
					Hong Kong,
					Iceland,
					Iran,
					Iraq,
					Ireland,
					Isle of Man,
					Ivory Coast,
					Jamaica,
					Jersey,
					Kazakhstan,
					Kenya,
					Kiribati,
					Kosovo,
					Kyrgyzstan,
					Laos,
					Lebanon,
					Lesotho,
					Liberia,
					Libya,
					Macau,
					Madagascar,
					Maldives,
					Malta,
					Marshall Islands,
					Mauritania,
					Mauritius,
					Mexico,
					Monaco,
					Montserrat,
					Morocco,
					Mozambique,
					Myanmar,
					Nauru
					Nepal,
					Nicaragua,
					Nigeria,
					Niue,
					Norfolk Island,
					North Korea,
					Northern Mariana Islands,
					Pakistan,
					Palau,
					Panama,
					Papua New Guinea,
					Paraguay,
					Peru,
					Pitcairn Islands,
					Puerto Rico,
					Republic of Cyprus,
					Republic of the Congo,
					Russia,
					Rwanda,
					Saint Barthélemy,
					Saint Helena, Ascension and Tristan da Cunha,
					Saint Kitts and Nevis,
					Saint Lucia,
					Saint Martin,
					Saint Vincent and the Grenadines,
					Senegal,
					Seychelles,
					Sierra Leone,
					Singapore,
					Solomon Islands,
					Somalia,
					South Georgia and the South Sandwich Islands,
					South Sudan,
					State of Palestine,
					Sudan,
					Suriname,
					Svalbard and Jan Mayen,
					Syria,
					São Tomé and Príncipe,
					Tajikistan,
					Togo,
					Tokelau,
					Tonga,
					Trinidad and Tobago,
					Turkmenistan,
					Turks and Caicos Islands,
					Tuvalu,
					Uganda,
					Ukraine,
					United States Minor Outlying Islands,
					United States Virgin Islands,
					Uzbekistan,
					Vanuatu,
					Vatican City,
					Venezuela,
					Vietnam,
					Western Sahara,
					Yemen,
					Zambia,
					Zimbabwe,
					Åland Islands
			</div>
			<div class="col-lg-6 pt-4 pt-lg-0" data-aos="fade-up" data-aos-delay="300">
				<p style="text-align:justify">
					&nbsp; &nbsp;<br />
					<a style="width: 300px; height: 300px;" /></a></p>
				<br />
				<br />
				<span style="text-align: justify;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span><a </a></div>
		</div>
	</div>
</section>
<br />
